# Generated by Django 5.2.6 on 2025-10-16 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas_clinicas', 'migration_rutas_mejoradas'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rutaclinica',
            name='rutas_clini_porcent_8551dc_idx',
        ),
        migrations.AlterField(
            model_name='rutaclinica',
            name='esta_pausado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rutaclinica',
            name='etapa_actual',
            field=models.CharField(blank=True, choices=[('CONSULTA_MEDICA', 'Consulta Médica'), ('PROCESO_EXAMEN', 'Proceso del Examen'), ('REVISION_EXAMEN', 'Revisión del Examen'), ('HOSPITALIZACION', 'Hospitalización'), ('OPERACION', 'Operación'), ('ALTA', 'Alta Médica')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rutaclinica',
            name='etapas_completadas',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='rutaclinica',
            name='etapas_seleccionadas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de etapas en orden'),
        ),
        migrations.AlterField(
            model_name='rutaclinica',
            name='fecha_estimada_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rutaclinica',
            name='fecha_fin_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rutaclinica',
            name='indice_etapa_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rutaclinica',
            name='metadatos_adicionales',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='rutaclinica',
            name='motivo_pausa',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rutaclinica',
            name='porcentaje_completado',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='rutaclinica',
            name='timestamps_etapas',
            field=models.JSONField(default=dict, help_text='Timestamps y detalles de cada etapa'),
        ),
    ]
