# Generated by Django 5.2.6 on 2025-09-24 22:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaClinica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_estimada_fin', models.DateTimeField(blank=True, help_text='Fecha estimada de finalización del proceso', null=True)),
                ('fecha_fin_real', models.DateTimeField(blank=True, help_text='Fecha real de finalización del proceso', null=True)),
                ('porcentaje_completado', models.FloatField(default=0.0, help_text='Porcentaje de completitud del proceso (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('estado', models.CharField(choices=[('INICIADA', 'Iniciada'), ('EN_PROGRESO', 'En Progreso'), ('PAUSADA', 'Pausada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='INICIADA', max_length=15)),
                ('metadatos_adicionales', models.JSONField(blank=True, default=dict, help_text='Información adicional del proceso en formato JSON')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_clinicas', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Ruta Clínica',
                'verbose_name_plural': 'Rutas Clínicas',
                'db_table': 'rutas_clinicas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EtapaRuta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_etapa', models.CharField(choices=[('CHECK_IN', 'Check-in'), ('ESPERA_CONSULTA', 'Espera Consulta'), ('CONSULTA', 'Consulta Médica'), ('DERIVACION', 'Derivación'), ('ESPERA_EXAMEN', 'Espera Examen'), ('EXAMEN', 'Examen/Procedimiento'), ('RESULTADOS', 'Espera Resultados'), ('CONTROL', 'Control/Segunda Consulta'), ('ALTA', 'Alta Médica'), ('ADMINISTRATIVO', 'Proceso Administrativo')], default='CONSULTA', max_length=20)),
                ('orden', models.PositiveIntegerField(help_text='Orden de la etapa en la secuencia (1, 2, 3...)')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_estimada', models.PositiveIntegerField(help_text='Duración estimada en minutos')),
                ('duracion_real', models.PositiveIntegerField(blank=True, help_text='Duración real en minutos', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('PAUSADA', 'Pausada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15)),
                ('es_estatico', models.BooleanField(default=False, help_text='True si la etapa está en espera de proceso externo')),
                ('motivo_pausa', models.TextField(blank=True, help_text='Motivo por el cual la etapa está pausada o es estática')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la etapa')),
                ('configuracion_etapa', models.JSONField(blank=True, default=dict, help_text='Configuraciones específicas de la etapa')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ruta_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='rutas_clinicas.rutaclinica')),
            ],
            options={
                'verbose_name': 'Etapa de Ruta',
                'verbose_name_plural': 'Etapas de Ruta',
                'db_table': 'etapas_ruta',
                'ordering': ['ruta_clinica', 'orden'],
            },
        ),
        migrations.AddIndex(
            model_name='rutaclinica',
            index=models.Index(fields=['paciente'], name='rutas_clini_pacient_0baade_idx'),
        ),
        migrations.AddIndex(
            model_name='rutaclinica',
            index=models.Index(fields=['estado'], name='rutas_clini_estado_6f4fae_idx'),
        ),
        migrations.AddIndex(
            model_name='rutaclinica',
            index=models.Index(fields=['fecha_inicio'], name='rutas_clini_fecha_i_064db3_idx'),
        ),
        migrations.AddIndex(
            model_name='rutaclinica',
            index=models.Index(fields=['porcentaje_completado'], name='rutas_clini_porcent_8551dc_idx'),
        ),
        migrations.AddIndex(
            model_name='etaparuta',
            index=models.Index(fields=['ruta_clinica', 'orden'], name='etapas_ruta_ruta_cl_1c4327_idx'),
        ),
        migrations.AddIndex(
            model_name='etaparuta',
            index=models.Index(fields=['estado'], name='etapas_ruta_estado_9ddb14_idx'),
        ),
        migrations.AddIndex(
            model_name='etaparuta',
            index=models.Index(fields=['tipo_etapa'], name='etapas_ruta_tipo_et_1fb77b_idx'),
        ),
        migrations.AddIndex(
            model_name='etaparuta',
            index=models.Index(fields=['es_estatico'], name='etapas_ruta_es_esta_c8a4d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='etaparuta',
            unique_together={('ruta_clinica', 'orden')},
        ),
    ]
