# Generated by Django 5.2.6 on 2025-10-22 00:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaClinica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('etapas_seleccionadas', models.JSONField(blank=True, default=list, help_text='Lista de etapas en orden')),
                ('etapa_actual', models.CharField(blank=True, choices=[('CONSULTA_MEDICA', 'Consulta Médica'), ('PROCESO_EXAMEN', 'Proceso del Examen'), ('REVISION_EXAMEN', 'Revisión del Examen'), ('HOSPITALIZACION', 'Hospitalización'), ('OPERACION', 'Operación'), ('ALTA', 'Alta Médica')], max_length=30, null=True)),
                ('indice_etapa_actual', models.PositiveIntegerField(default=0)),
                ('etapas_completadas', models.JSONField(default=list)),
                ('timestamps_etapas', models.JSONField(default=dict, help_text='Timestamps y detalles de cada etapa')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_estimada_fin', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_real', models.DateTimeField(blank=True, null=True)),
                ('porcentaje_completado', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('estado', models.CharField(choices=[('INICIADA', 'Iniciada'), ('EN_PROGRESO', 'En Progreso'), ('PAUSADA', 'Pausada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='INICIADA', max_length=15)),
                ('esta_pausado', models.BooleanField(default=False)),
                ('motivo_pausa', models.TextField(blank=True)),
                ('metadatos_adicionales', models.JSONField(blank=True, default=dict)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('historial_cambios', models.JSONField(default=list, help_text='Registro de todos los cambios de etapa')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_clinicas', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Ruta Clínica',
                'verbose_name_plural': 'Rutas Clínicas',
                'db_table': 'rutas_clinicas',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['paciente'], name='rutas_clini_pacient_0baade_idx'), models.Index(fields=['estado'], name='rutas_clini_estado_6f4fae_idx'), models.Index(fields=['fecha_inicio'], name='rutas_clini_fecha_i_064db3_idx'), models.Index(fields=['etapa_actual'], name='rutas_clini_etapa_a_1427ca_idx')],
            },
        ),
    ]
