# Generated by Django 5.2.6 on 2025-10-31 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas_clinicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutaclinica',
            name='tiempo_pausado_acumulado',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Tiempo total que la ruta ha estado en PAUSA'),
        ),
    ]
