# Generated by Django 5.2.6 on 2025-10-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('rutas_clinicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='etaparuta',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='etaparuta',
            name='ruta_clinica',
        ),
        migrations.AddField(
            model_name='rutaclinica',
            name='esta_pausado',
            field=models.BooleanField(default=False, help_text='Indica si la ruta está actualmente pausada'),
        ),
        migrations.AddField(
            model_name='rutaclinica',
            name='etapa_actual',
            field=models.CharField(blank=True, choices=[('CONSULTA_MEDICA', 'Consulta Médica'), ('PROCESO_EXAMEN', 'Proceso del Examen'), ('REVISION_EXAMEN', 'Revisión del Examen'), ('HOSPITALIZACION', 'Hospitalización y Operado')], help_text='Etapa actual en la que se encuentra el paciente', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rutaclinica',
            name='etapas_completadas',
            field=models.JSONField(default=list, help_text='Lista de etapas ya completadas'),
        ),
        migrations.AddField(
            model_name='rutaclinica',
            name='etapas_seleccionadas',
            field=models.JSONField(default=list, help_text="Lista de etapas seleccionadas en orden: ['CONSULTA_MEDICA', 'PROCESO_EXAMEN', ...]"),
        ),
        migrations.AddField(
            model_name='rutaclinica',
            name='indice_etapa_actual',
            field=models.PositiveIntegerField(default=0, help_text='Índice de la etapa actual en la lista de etapas'),
        ),
        migrations.AddField(
            model_name='rutaclinica',
            name='motivo_pausa',
            field=models.TextField(blank=True, help_text='Motivo por el cual está pausada la ruta'),
        ),
        migrations.AddField(
            model_name='rutaclinica',
            name='timestamps_etapas',
            field=models.JSONField(default=dict, help_text='Diccionario con fecha_inicio y fecha_fin de cada etapa'),
        ),
        migrations.AddIndex(
            model_name='rutaclinica',
            index=models.Index(fields=['etapa_actual'], name='rutas_clini_etapa_a_1427ca_idx'),
        ),
        migrations.DeleteModel(
            name='EtapaRuta',
        ),
    ]
