# Generated by Django 5.2.6 on 2025-10-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas_clinicas', '0002_alter_etaparuta_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutaclinica',
            name='etapas_seleccionadas',
            field=models.JSONField(blank=True, default=list, help_text="Lista de etapas seleccionadas en orden: ['CONSULTA_MEDICA', 'PROCESO_EXAMEN', ...]"),
        ),
    ]
