# Generated by Django 5.2.6 on 2025-10-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas_clinicas', '0003_alter_rutaclinica_etapas_seleccionadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutaclinica',
            name='etapa_actual',
            field=models.CharField(blank=True, choices=[('CONSULTA_MEDICA', 'Consulta Médica'), ('PROCESO_EXAMEN', 'Proceso del Examen'), ('REVISION_EXAMEN', 'Revisión del Examen'), ('HOSPITALIZACION', 'Hospitalización'), ('OPERACION', 'Operado'), ('ALTA', 'Alta')], help_text='Etapa actual en la que se encuentra el paciente', max_length=30, null=True),
        ),
    ]
