# Generated by Django 5.2.6 on 2025-11-17 05:42

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rut', models.CharField(default='', help_text='RUT en formato chileno XX.XXX.XXX-X', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe estar en formato chileno: XX.XXX.XXX-X (ejemplo: 21.376.932-3)', regex='^\\d{1,2}\\.?\\d{3}\\.?\\d{3}-[0-9kK]$')])),
                ('identificador_hash', models.CharField(db_index=True, default='', editable=False, help_text='Hash SHA-256 del RUT para proteger privacidad', max_length=64, unique=True)),
                ('nombre', models.CharField(blank=True, default='', help_text='Nombre(s) del paciente', max_length=100, null=True)),
                ('apellido_paterno', models.CharField(blank=True, default='', help_text='Apellido paterno del paciente', max_length=100, null=True)),
                ('apellido_materno', models.CharField(blank=True, default='', help_text='Apellido materno del paciente (opcional)', max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento del paciente', null=True)),
                ('edad', models.PositiveIntegerField(editable=False, help_text='Edad calculada automáticamente desde fecha de nacimiento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('NE', 'No Especifica')], default='NE', max_length=2)),
                ('correo', models.EmailField(blank=True, default='', help_text='Correo electrónico del paciente', max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('telefono', models.CharField(blank=True, default='', help_text='Teléfono celular en formato +56912345678', max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe estar en formato chileno: +56912345678', regex='^\\+56\\d{9}$')])),
                ('telefono_emergencia', models.CharField(blank=True, help_text='Teléfono de contacto de emergencia (opcional)', max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe estar en formato chileno: +56912345678', regex='^\\+56\\d{9}$')])),
                ('nombre_contacto_emergencia', models.CharField(blank=True, help_text='Nombre del contacto de emergencia', max_length=200, null=True)),
                ('direccion_calle', models.CharField(blank=True, default='', help_text='Calle y número', max_length=255, null=True)),
                ('direccion_comuna', models.CharField(blank=True, default='', help_text='Comuna', max_length=100, null=True)),
                ('direccion_ciudad', models.CharField(blank=True, default='', help_text='Ciudad', max_length=100, null=True)),
                ('direccion_region', models.CharField(blank=True, choices=[('XV', 'Región de Arica y Parinacota'), ('I', 'Región de Tarapacá'), ('II', 'Región de Antofagasta'), ('III', 'Región de Atacama'), ('IV', 'Región de Coquimbo'), ('V', 'Región de Valparaíso'), ('RM', 'Región Metropolitana de Santiago'), ('VI', "Región del Libertador General Bernardo O'Higgins"), ('VII', 'Región del Maule'), ('XVI', 'Región de Ñuble'), ('VIII', 'Región del Biobío'), ('IX', 'Región de La Araucanía'), ('XIV', 'Región de Los Ríos'), ('X', 'Región de Los Lagos'), ('XI', 'Región Aysén del General Carlos Ibáñez del Campo'), ('XII', 'Región de Magallanes y de la Antártica Chilena')], default='', help_text='Región de Chile', max_length=5, null=True)),
                ('direccion_codigo_postal', models.CharField(blank=True, default='Sin proporcionar', help_text='Código postal (opcional)', max_length=10, null=True)),
                ('seguro_medico', models.CharField(choices=[('FONASA_A', 'FONASA Tramo A'), ('FONASA_B', 'FONASA Tramo B'), ('FONASA_C', 'FONASA Tramo C'), ('FONASA_D', 'FONASA Tramo D'), ('ISAPRE_BANMEDICA', 'Isapre Banmédica'), ('ISAPRE_COLMENA', 'Isapre Colmena'), ('ISAPRE_CONSALUD', 'Isapre Consalud'), ('ISAPRE_CRUZBANCA', 'Isapre Cruz Blanca'), ('ISAPRE_VIDATRES', 'Isapre Vida Tres'), ('ISAPRE_NUEVA_MASVIDA', 'Isapre Nueva Masvida'), ('ISAPRE_ESENCIAL', 'Isapre Esencial'), ('PARTICULAR', 'Particular (Sin Previsión)'), ('OTRO', 'Otro')], default='PARTICULAR', help_text='Sistema de salud al que pertenece', max_length=30)),
                ('numero_beneficiario', models.CharField(blank=True, default='Sin proporcionar', help_text='Número de beneficiario o afiliado (opcional)', max_length=50)),
                ('tipo_sangre', models.CharField(choices=[('A+', 'A Positivo'), ('A-', 'A Negativo'), ('B+', 'B Positivo'), ('B-', 'B Negativo'), ('AB+', 'AB Positivo'), ('AB-', 'AB Negativo'), ('O+', 'O Positivo'), ('O-', 'O Negativo'), ('DESCONOCIDO', 'Desconocido')], default='DESCONOCIDO', help_text='Tipo de sangre del paciente', max_length=15)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kilogramos', max_digits=5, null=True)),
                ('altura', models.PositiveIntegerField(blank=True, help_text='Altura en centímetros', null=True)),
                ('alergias', models.TextField(blank=True, help_text='Alergias conocidas del paciente')),
                ('condiciones_preexistentes', models.TextField(blank=True, help_text='Condiciones médicas preexistentes')),
                ('medicamentos_actuales', models.TextField(blank=True, help_text='Medicamentos que toma actualmente')),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de ingreso al sistema')),
                ('estado_actual', models.CharField(choices=[('EN_ESPERA', 'En Espera'), ('ACTIVO', 'Activo en Proceso'), ('PROCESO_PAUSADO', 'Proceso Pausado'), ('ALTA_COMPLETA', 'Alta Completa'), ('PROCESO_CANCELADO', 'Proceso Cancelado'), ('INACTIVO', 'Inactivo/Historial')], default='EN_ESPERA', help_text='Estado general del paciente en el sistema', max_length=20)),
                ('etapa_actual', models.CharField(blank=True, choices=[('CONSULTA_MEDICA', 'Consulta Médica'), ('PROCESO_EXAMEN', 'Proceso del Examen'), ('REVISION_EXAMEN', 'Revisión del Examen'), ('HOSPITALIZACION', 'Hospitalización'), ('OPERACION', 'Operación'), ('ALTA', 'Alta Médica')], help_text='Etapa actual del flujo clínico (sincronizada con RutaClinica)', max_length=30, null=True)),
                ('nivel_urgencia', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('metadatos_adicionales', models.JSONField(blank=True, default=dict, help_text='Información adicional en formato JSON (dict)')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'pacientes',
                'ordering': ['-fecha_ingreso'],
                'indexes': [models.Index(fields=['rut'], name='pacientes_rut_1a1723_idx'), models.Index(fields=['identificador_hash'], name='pacientes_identif_568f69_idx'), models.Index(fields=['estado_actual'], name='pacientes_estado__5e8350_idx'), models.Index(fields=['etapa_actual'], name='pacientes_etapa_a_c50f75_idx'), models.Index(fields=['fecha_ingreso'], name='pacientes_fecha_i_709aca_idx'), models.Index(fields=['nivel_urgencia'], name='pacientes_nivel_u_c63f0d_idx'), models.Index(fields=['apellido_paterno', 'apellido_materno'], name='pacientes_apellid_12f11c_idx')],
            },
        ),
    ]
