# Generated by Django 5.2.6 on 2025-09-24 22:01

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identificador_hash', models.CharField(help_text='Hash del RUT/identificador para proteger privacidad', max_length=64, unique=True)),
                ('edad', models.PositiveIntegerField(help_text='Edad del paciente en años')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('NE', 'No Especifica')], default='NE', max_length=2)),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de ingreso al sistema')),
                ('estado_actual', models.CharField(choices=[('EN_ESPERA', 'En Espera'), ('EN_CONSULTA', 'En Consulta'), ('EN_EXAMEN', 'En Exámen'), ('PROCESO_PAUSADO', 'Proceso Pausado'), ('ALTA_COMPLETA', 'Alta Completa'), ('PROCESO_INCOMPLETO', 'Proceso Incompleto')], default='EN_ESPERA', max_length=20)),
                ('nivel_urgencia', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('metadatos_adicionales', models.JSONField(blank=True, default=dict, help_text='Información adicional en formato JSON')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'pacientes',
                'ordering': ['-fecha_ingreso'],
                'indexes': [models.Index(fields=['identificador_hash'], name='pacientes_identif_568f69_idx'), models.Index(fields=['estado_actual'], name='pacientes_estado__5e8350_idx'), models.Index(fields=['fecha_ingreso'], name='pacientes_fecha_i_709aca_idx')],
            },
        ),
    ]
