# Generated by Django 5.2.6 on 2025-10-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', 'patient_migration'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paciente',
            new_name='pacientes_nivel_u_c63f0d_idx',
            old_name='pacientes_nivel_u_idx',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='metadatos_adicionales',
            field=models.JSONField(blank=True, default=dict, help_text='Información adicional en formato JSON (dict)'),
        ),
    ]
