# Generated by Django 5.2.6 on 2025-10-22 02:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='apellido_materno',
            field=models.CharField(blank=True, default='', help_text='Apellido materno del paciente (opcional)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellido_paterno',
            field=models.CharField(blank=True, default='', help_text='Apellido paterno del paciente', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='correo',
            field=models.EmailField(blank=True, default='', help_text='Correo electrónico del paciente', max_length=254, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion_calle',
            field=models.CharField(blank=True, default='', help_text='Calle y número', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion_ciudad',
            field=models.CharField(blank=True, default='', help_text='Ciudad', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion_codigo_postal',
            field=models.CharField(blank=True, default='Sin proporcionar', help_text='Código postal (opcional)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion_comuna',
            field=models.CharField(blank=True, default='', help_text='Comuna', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion_region',
            field=models.CharField(blank=True, choices=[('XV', 'Región de Arica y Parinacota'), ('I', 'Región de Tarapacá'), ('II', 'Región de Antofagasta'), ('III', 'Región de Atacama'), ('IV', 'Región de Coquimbo'), ('V', 'Región de Valparaíso'), ('RM', 'Región Metropolitana de Santiago'), ('VI', "Región del Libertador General Bernardo O'Higgins"), ('VII', 'Región del Maule'), ('XVI', 'Región de Ñuble'), ('VIII', 'Región del Biobío'), ('IX', 'Región de La Araucanía'), ('XIV', 'Región de Los Ríos'), ('X', 'Región de Los Lagos'), ('XI', 'Región Aysén del General Carlos Ibáñez del Campo'), ('XII', 'Región de Magallanes y de la Antártica Chilena')], default='', help_text='Región de Chile', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del paciente', null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre(s) del paciente', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, default='', help_text='Teléfono celular en formato +56912345678', max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe estar en formato chileno: +56912345678', regex='^\\+56\\d{9}$')]),
        ),
    ]
