# Generated by Django 5.2.6 on 2025-10-27 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_agregar_etapa_actual'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paciente',
            new_name='pacientes_etapa_a_c50f75_idx',
            old_name='pacientes_etapa_a_idx',
        ),
    ]
