# Generated by Django 5.2.6 on 2025-10-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_rename_pacientes_etapa_a_idx_pacientes_etapa_a_c50f75_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='estado_actual',
            field=models.CharField(choices=[('EN_ESPERA', 'En Espera'), ('ACTIVO', 'Activo en Proceso'), ('PROCESO_PAUSADO', 'Proceso Pausado'), ('ALTA_COMPLETA', 'Alta Completa'), ('PROCESO_CANCELADO', 'Proceso Cancelado'), ('INACTIVO', 'Inactivo/Historial')], default='EN_ESPERA', help_text='Estado general del paciente en el sistema', max_length=20),
        ),
    ]
