# Generated by Django 5.2.6 on 2025-10-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_alter_paciente_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.PositiveIntegerField(editable=False, help_text='Edad calculada automáticamente desde fecha de nacimiento'),
        ),
    ]
