# Generated by Django 5.2.6 on 2025-10-22 03:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_alter_paciente_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(default='', help_text='RUT en formato chileno XX.XXX.XXX-X', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe estar en formato chileno: XX.XXX.XXX-X (ejemplo: 21.376.932-3)', regex='^\\d{1,3}\\.\\d{3}\\.\\d{3}-[0-9kK]$')]),
        ),
    ]
