# Generated by Django 5.2.6 on 2025-11-17 05:42

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetricas',
            fields=[
            ],
            options={
                'verbose_name': 'Métrica del Sistema',
                'verbose_name_plural': '📊 Dashboard y Métricas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pacientes.paciente',),
        ),
    ]
