# Generated by Django 5.2.6 on 2025-10-23 22:12

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clave', models.CharField(help_text='Clave única de la configuración', max_length=100, unique=True)),
                ('valor', models.TextField(help_text='Valor de la configuración')),
                ('tipo_dato', models.CharField(choices=[('STRING', 'Texto'), ('INTEGER', 'Número Entero'), ('FLOAT', 'Número Decimal'), ('BOOLEAN', 'Booleano'), ('JSON', 'JSON'), ('DATE', 'Fecha'), ('DATETIME', 'Fecha y Hora')], default='STRING', max_length=10)),
                ('descripcion', models.TextField(help_text='Descripción de para qué sirve esta configuración')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'db_table': 'configuraciones_sistema',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='IntegracionExterna',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_sistema', models.CharField(help_text='Nombre del sistema externo (ej: Rayen, Fonendo)', max_length=100)),
                ('tipo_sistema', models.CharField(choices=[('HIS', 'Sistema de Información Hospitalaria'), ('EMR', 'Registro Médico Electrónico'), ('LIS', 'Sistema de Información de Laboratorio'), ('RIS', 'Sistema de Información Radiológica'), ('PACS', 'Sistema de Archivo y Comunicación de Imágenes'), ('API_EXTERNA', 'API Externa'), ('WEBHOOK', 'Webhook'), ('OTRO', 'Otro Sistema')], default='HIS', max_length=15)),
                ('endpoint_base_url', models.URLField(help_text='URL base del sistema externo', validators=[django.core.validators.URLValidator()])),
                ('metodo_autenticacion', models.CharField(choices=[('API_KEY', 'API Key'), ('BEARER_TOKEN', 'Bearer Token'), ('BASIC_AUTH', 'Autenticación Básica'), ('OAUTH2', 'OAuth 2.0'), ('JWT', 'JSON Web Token'), ('CUSTOM', 'Método Personalizado')], default='API_KEY', max_length=15)),
                ('token_acceso_encrypted', models.TextField(help_text='Token de acceso encriptado para seguridad')),
                ('ultima_sincronizacion', models.DateTimeField(blank=True, help_text='Última sincronización exitosa', null=True)),
                ('estado_conexion', models.CharField(choices=[('ACTIVA', 'Conexión Activa'), ('INACTIVA', 'Conexión Inactiva'), ('ERROR', 'Error de Conexión'), ('MANTENIMIENTO', 'En Mantenimiento'), ('CONFIGURACION', 'En Configuración')], default='CONFIGURACION', max_length=15)),
                ('configuracion_mapeo', models.JSONField(blank=True, default=dict, help_text='Mapeo de campos entre sistemas')),
                ('intervalo_sincronizacion', models.PositiveIntegerField(default=300, help_text='Intervalo de sincronización en segundos')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integración Externa',
                'verbose_name_plural': 'Integraciones Externas',
                'db_table': 'integraciones_externas',
                'ordering': ['nombre_sistema'],
            },
        ),
        migrations.CreateModel(
            name='LogSincronizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('EXITOSA', 'Exitosa'), ('ERROR', 'Error'), ('ADVERTENCIA', 'Advertencia'), ('WEBHOOK_PROCESADO', 'Webhook Procesado'), ('TIMEOUT', 'Timeout'), ('DATOS_INVALIDOS', 'Datos Inválidos')], max_length=20)),
                ('mensaje', models.TextField()),
                ('datos_adicionales', models.JSONField(blank=True, default=dict, help_text='Datos adicionales sobre la sincronización')),
                ('tiempo_respuesta_ms', models.PositiveIntegerField(blank=True, help_text='Tiempo de respuesta en milisegundos', null=True)),
            ],
            options={
                'verbose_name': 'Log de Sincronización',
                'verbose_name_plural': 'Logs de Sincronización',
                'db_table': 'logs_sincronizacion',
                'ordering': ['-timestamp'],
            },
        ),
    ]
