# Generated by Django 5.2.6 on 2025-10-22 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integraciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última modificación', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='integracionexterna',
            name='usuario_configuracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integraciones_configuradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logsincronizacion',
            name='integracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_sincronizacion', to='integraciones.integracionexterna'),
        ),
        migrations.AddIndex(
            model_name='configuracionsistema',
            index=models.Index(fields=['clave'], name='configuraci_clave_8e7920_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionsistema',
            index=models.Index(fields=['activo'], name='configuraci_activo_9adf35_idx'),
        ),
        migrations.AddIndex(
            model_name='integracionexterna',
            index=models.Index(fields=['nombre_sistema'], name='integracion_nombre__23079f_idx'),
        ),
        migrations.AddIndex(
            model_name='integracionexterna',
            index=models.Index(fields=['estado_conexion'], name='integracion_estado__5f2d08_idx'),
        ),
        migrations.AddIndex(
            model_name='integracionexterna',
            index=models.Index(fields=['activo'], name='integracion_activo_6acff8_idx'),
        ),
        migrations.AddIndex(
            model_name='logsincronizacion',
            index=models.Index(fields=['integracion', '-timestamp'], name='logs_sincro_integra_b282ca_idx'),
        ),
        migrations.AddIndex(
            model_name='logsincronizacion',
            index=models.Index(fields=['estado'], name='logs_sincro_estado_b53f82_idx'),
        ),
    ]
