# Generated by Django 5.2.6 on 2025-11-17 05:42

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(help_text='Número identificador del box (ej: BOX-001, SALA-A)', max_length=10, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del box', max_length=100)),
                ('especialidad', models.CharField(choices=[('GENERAL', 'Medicina General'), ('CARDIOLOGIA', 'Cardiología'), ('NEUROLOGIA', 'Neurología'), ('PEDIATRIA', 'Pediatría'), ('GINECOLOGIA', 'Ginecología'), ('TRAUMATOLOGIA', 'Traumatología'), ('OFTALMOLOGIA', 'Oftalmología'), ('DERMATOLOGIA', 'Dermatología'), ('PSIQUIATRIA', 'Psiquiatría'), ('RADIOLOGIA', 'Radiología'), ('LABORATORIO', 'Laboratorio'), ('PROCEDIMIENTOS', 'Procedimientos'), ('CIRUGIA_MENOR', 'Cirugía Menor'), ('MULTIUSO', 'Multiuso')], default='GENERAL', max_length=20)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('MANTENIMIENTO', 'En Mantenimiento'), ('FUERA_SERVICIO', 'Fuera de Servicio')], default='DISPONIBLE', max_length=15)),
                ('capacidad_maxima', models.PositiveIntegerField(default=1, help_text='Número máximo de personas que puede atender simultáneamente', validators=[django.core.validators.MinValueValidator(1)])),
                ('equipamiento', models.JSONField(blank=True, default=list, help_text='Lista de equipamiento disponible en el box')),
                ('horarios_disponibles', models.JSONField(blank=True, default=dict, help_text='Horarios de disponibilidad por día de la semana')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tiempo_ocupado_hoy', models.DurationField(default=datetime.timedelta, help_text='Tiempo total ocupado en el día actual')),
                ('ultima_ocupacion', models.DateTimeField(blank=True, help_text='Última vez que el box fue ocupado', null=True)),
                ('ultima_liberacion', models.DateTimeField(blank=True, help_text='Última vez que el box fue liberado', null=True)),
            ],
            options={
                'verbose_name': 'Box',
                'verbose_name_plural': 'Boxes',
                'db_table': 'boxes',
                'ordering': ['numero'],
                'indexes': [models.Index(fields=['numero'], name='boxes_numero_3c1291_idx'), models.Index(fields=['estado'], name='boxes_estado_e21d0c_idx'), models.Index(fields=['especialidad'], name='boxes_especia_535e95_idx'), models.Index(fields=['activo'], name='boxes_activo_6e4a71_idx')],
            },
        ),
        migrations.CreateModel(
            name='OcupacionManual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duracion_minutos', models.PositiveIntegerField(help_text='Duración de la ocupación en minutos')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, help_text='Momento en que se ocupó el box')),
                ('fecha_fin_programada', models.DateTimeField(help_text='Momento programado para liberar el box')),
                ('fecha_fin_real', models.DateTimeField(blank=True, help_text='Momento real en que se liberó el box', null=True)),
                ('motivo', models.CharField(blank=True, help_text='Motivo de la ocupación manual', max_length=200)),
                ('activa', models.BooleanField(default=True, help_text='Si la ocupación sigue activa')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocupaciones_manuales', to='boxes.box')),
            ],
            options={
                'verbose_name': 'Ocupación Manual',
                'verbose_name_plural': 'Ocupaciones Manuales',
                'db_table': 'ocupaciones_manuales',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['box', 'activa'], name='ocupaciones_box_id_b2216a_idx'), models.Index(fields=['fecha_fin_programada'], name='ocupaciones_fecha_f_9fbec8_idx')],
            },
        ),
    ]
