# Generated by Django 5.2.6 on 2025-10-24 05:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcupacionManual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duracion_minutos', models.PositiveIntegerField(help_text='Duración de la ocupación en minutos')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, help_text='Momento en que se ocupó el box')),
                ('fecha_fin_programada', models.DateTimeField(help_text='Momento programado para liberar el box')),
                ('fecha_fin_real', models.DateTimeField(blank=True, help_text='Momento real en que se liberó el box', null=True)),
                ('motivo', models.CharField(blank=True, help_text='Motivo de la ocupación manual', max_length=200)),
                ('activa', models.BooleanField(default=True, help_text='Si la ocupación sigue activa')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocupaciones_manuales', to='boxes.box')),
            ],
            options={
                'verbose_name': 'Ocupación Manual',
                'verbose_name_plural': 'Ocupaciones Manuales',
                'db_table': 'ocupaciones_manuales',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['box', 'activa'], name='ocupaciones_box_id_b2216a_idx'), models.Index(fields=['fecha_fin_programada'], name='ocupaciones_fecha_f_9fbec8_idx')],
            },
        ),
    ]
