# Generated by Django 5.2.6 on 2025-11-17 05:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_medico', models.CharField(help_text='Código único del médico en el sistema hospitalario', max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('especialidad_principal', models.CharField(choices=[('MEDICINA_GENERAL', 'Medicina General'), ('MEDICINA_INTERNA', 'Medicina Interna'), ('CARDIOLOGIA', 'Cardiología'), ('NEUROLOGIA', 'Neurología'), ('PEDIATRIA', 'Pediatría'), ('GINECOLOGIA', 'Ginecología y Obstetricia'), ('TRAUMATOLOGIA', 'Traumatología y Ortopedia'), ('OFTALMOLOGIA', 'Oftalmología'), ('DERMATOLOGIA', 'Dermatología'), ('PSIQUIATRIA', 'Psiquiatría'), ('RADIOLOGIA', 'Radiología'), ('ANESTESIOLOGIA', 'Anestesiología'), ('CIRUGIA_GENERAL', 'Cirugía General'), ('UROLOGIA', 'Urología'), ('OTORRINOLARINGOLOGIA', 'Otorrinolaringología'), ('ENFERMERIA', 'Enfermería'), ('KINESIOLOGO', 'Kinesiología'), ('PSICOLOGO', 'Psicología'), ('NUTRICIONISTA', 'Nutrición'), ('TECNICO_ENFERMERIA', 'Técnico en Enfermería'), ('TECNICO_RADIOLOGIA', 'Técnico en Radiología'), ('OTRO', 'Otra Especialidad')], default='MEDICINA_GENERAL', max_length=30)),
                ('especialidades_secundarias', models.JSONField(blank=True, default=list, help_text='Lista de especialidades secundarias')),
                ('horarios_atencion', models.JSONField(blank=True, default=dict, help_text='Horarios de atención por día de la semana')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('configuraciones_personales', models.JSONField(blank=True, default=dict, help_text='Configuraciones y preferencias personales del médico')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'db_table': 'medicos',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_hora_inicio', models.DateTimeField(help_text='Fecha y hora programada de inicio')),
                ('fecha_hora_fin', models.DateTimeField(blank=True, help_text='Fecha y hora programada de fin', null=True)),
                ('inicio_cronometro', models.DateTimeField(blank=True, help_text='Momento real de inicio de la atención', null=True)),
                ('fin_cronometro', models.DateTimeField(blank=True, help_text='Momento real de fin de la atención', null=True)),
                ('duracion_planificada', models.PositiveIntegerField(help_text='Duración planificada en minutos', validators=[django.core.validators.MinValueValidator(1)])),
                ('duracion_real', models.PositiveIntegerField(blank=True, help_text='Duración real en minutos', null=True)),
                ('tipo_atencion', models.CharField(choices=[('CONSULTA_GENERAL', 'Consulta General'), ('CONSULTA_ESPECIALIDAD', 'Consulta de Especialidad'), ('CONTROL', 'Control'), ('PROCEDIMIENTO', 'Procedimiento'), ('EXAMEN', 'Examen'), ('CIRUGIA_MENOR', 'Cirugía Menor'), ('URGENCIA', 'Atención de Urgencia'), ('TELEMEDICINA', 'Telemedicina'), ('INTERCONSULTA', 'Interconsulta')], default='CONSULTA_GENERAL', max_length=25)),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_ESPERA', 'En Espera'), ('EN_CURSO', 'En Curso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('NO_PRESENTADO', 'No se Presentó')], default='PROGRAMADA', max_length=15)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre la atención')),
                ('atraso_reportado', models.BooleanField(default=False, help_text='Indica si el médico reportó un atraso del paciente')),
                ('fecha_reporte_atraso', models.DateTimeField(blank=True, help_text='Momento en que se reportó el atraso', null=True)),
                ('motivo_atraso', models.TextField(blank=True, help_text='Motivo del atraso reportado por el médico')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atenciones', to='boxes.box')),
            ],
            options={
                'verbose_name': 'Atención',
                'verbose_name_plural': 'Atenciones',
                'db_table': 'atenciones',
                'ordering': ['-fecha_hora_inicio'],
            },
        ),
    ]
