# Generated by Django 5.2.6 on 2025-11-03 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='medico',
            field=models.ForeignKey(help_text='Usuario con rol de médico asignado a esta atención', limit_choices_to={'rol': 'MEDICO'}, on_delete=django.db.models.deletion.CASCADE, related_name='atenciones_medico', to=settings.AUTH_USER_MODEL),
        ),
    ]
