# Generated by Django 5.2.6 on 2025-11-17 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atenciones', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='medico',
            field=models.ForeignKey(help_text='Usuario con rol de médico asignado a esta atención', limit_choices_to={'rol': 'MEDICO'}, on_delete=django.db.models.deletion.CASCADE, related_name='atenciones_medico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atencion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atenciones', to='pacientes.paciente'),
        ),
        migrations.AddIndex(
            model_name='medico',
            index=models.Index(fields=['codigo_medico'], name='medicos_codigo__44d3a4_idx'),
        ),
        migrations.AddIndex(
            model_name='medico',
            index=models.Index(fields=['especialidad_principal'], name='medicos_especia_8198d5_idx'),
        ),
        migrations.AddIndex(
            model_name='medico',
            index=models.Index(fields=['activo'], name='medicos_activo_50c87a_idx'),
        ),
        migrations.AddIndex(
            model_name='atencion',
            index=models.Index(fields=['paciente'], name='atenciones_pacient_cb6388_idx'),
        ),
        migrations.AddIndex(
            model_name='atencion',
            index=models.Index(fields=['medico'], name='atenciones_medico__dcf36d_idx'),
        ),
        migrations.AddIndex(
            model_name='atencion',
            index=models.Index(fields=['box'], name='atenciones_box_id_4f2766_idx'),
        ),
        migrations.AddIndex(
            model_name='atencion',
            index=models.Index(fields=['fecha_hora_inicio'], name='atenciones_fecha_h_218b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='atencion',
            index=models.Index(fields=['estado'], name='atenciones_estado_aade7a_idx'),
        ),
        migrations.AddIndex(
            model_name='atencion',
            index=models.Index(fields=['tipo_atencion'], name='atenciones_tipo_at_9c23c3_idx'),
        ),
    ]
