# Generated by Django 5.2.6 on 2025-11-07 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0005_agregar_campos_atraso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='atraso_reportado',
        ),
        migrations.RemoveField(
            model_name='atencion',
            name='fecha_reporte_atraso',
        ),
        migrations.RemoveField(
            model_name='atencion',
            name='motivo_atraso',
        ),
    ]
