# Generated by Django 5.2.6 on 2025-11-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0006_remove_atencion_atraso_reportado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='atraso_reportado',
            field=models.BooleanField(default=False, help_text='Indica si el médico reportó un atraso del paciente'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='fecha_reporte_atraso',
            field=models.DateTimeField(blank=True, help_text='Momento en que se reportó el atraso', null=True),
        ),
        migrations.AddField(
            model_name='atencion',
            name='motivo_atraso',
            field=models.TextField(blank=True, help_text='Motivo del atraso reportado por el médico'),
        ),
    ]
