# Generated by Django 5.2.6 on 2025-11-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0007_atencion_atraso_reportado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='minutos_espera_atraso',
            field=models.PositiveIntegerField(default=5, help_text='Minutos de espera después de reportar atraso antes de marcar como no presentado'),
        ),
    ]
