# Generated by Django 5.2.6 on 2025-11-08 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0008_atencion_minutos_espera_atraso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='minutos_espera_atraso',
        ),
    ]
