# Generated by Django 5.2.6
# backend/users/migrations/0003_user_especialidad.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_rol_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='especialidad',
            field=models.CharField(
                blank=True, 
                choices=[
                    ('MEDICINA_GENERAL', 'Medicina General'),
                    ('PEDIATRIA', 'Pediatría'),
                    ('CARDIOLOGIA', 'Cardiología'),
                    ('DERMATOLOGIA', 'Dermatología'),
                    ('GINECOLOGIA', 'Ginecología'),
                    ('TRAUMATOLOGIA', 'Traumatología'),
                    ('OFTALMOLOGIA', 'Oftalmología'),
                    ('OTORRINOLARINGOLOGIA', 'Otorrinolaringología'),
                    ('NEUROLOGIA', 'Neurología'),
                    ('PSIQUIATRIA', 'Psiquiatría'),
                    ('URGENCIAS', 'Medicina de Urgencias'),
                    ('MEDICINA_INTERNA', 'Medicina Interna'),
                    ('CIRUGIA_GENERAL', 'Cirugía General'),
                    ('ANESTESIOLOGIA', 'Anestesiología'),
                    ('RADIOLOGIA', 'Radiología'),
                ], 
                help_text='Solo aplicable para usuarios con rol Médico', 
                max_length=30, 
                null=True, 
                verbose_name='Especialidad Médica'
            ),
        ),
    ]